# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CZInstagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CZInstagram
  
  pod 'SwiftHTTP', '~> 2.0.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire', '~> 4.4'
  pod 'SDWebImage', '~> 4.0' 
  pod 'EasyMapping', '~> 0.20'
  pod 'Reveal-SDK’
  
  target 'CZInstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CZInstagramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
